
# the latest version does not depend on zookeeper.
services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_KRAFT_MODE=yes                         # ✅ Enable KRaft mode
      - KAFKA_CFG_PROCESS_ROLES=broker,controller    # ✅ Required roles
      - KAFKA_CFG_NODE_ID=1                          # ✅ Unique node ID
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
      - ALLOW_PLAINTEXT_LISTENER=yes
#    volumes:
#      - ./kafka-data:/bitnami/kafka            # ✅ Mounts to ./socialDemo/kafka-data

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
#    volumes:
#      - ./redis-data:/data

  postgres:
    image: postgres:16.8
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=social
      - POSTGRES_PASSWORD=social
    volumes:
      - ./postgres-data:/var/lib/postgresql/data